Replace .travis.yml
This script now generated by the make-travis-yml.hs script from hvr/multi-ghc-travis. It has been lightly edited to only test ghc-7.8.4 and ghc-7.10.2.

This script no longer pulls the accelerate dependency from github. That is incompatible with our goal of caching. oops...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,75 +1,83 @@
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
 language: c
 sudo: false
-
-# NOTE: travis won't let us expand variables in the addons section ):
-matrix:
-  include:
-    - compiler: "GHC 7.8.4"
-      env:
-        GHC=7.8.4
-        CABAL=1.18
-        URL_ACCELERATE=https://github.com/AccelerateHS/accelerate.git
-        SHA_ACCELERATE=15aedff344232893c89e513c1caf4bcf699a2b86
-      addons:
-        apt:
-          sources:
-            - hvr-ghc
-          packages:
-            - cabal-install-1.18
-            - ghc-7.8.4
-
-    - compiler: "GHC 7.10.2"
-      env:
-        GHC=7.10.2
-        CABAL=1.22
-        URL_ACCELERATE=https://github.com/AccelerateHS/accelerate.git
-        SHA_ACCELERATE=15aedff344232893c89e513c1caf4bcf699a2b86
-      addons:
-        apt:
-          sources:
-            - hvr-ghc
-          packages:
-            - cabal-install-1.22
-            - ghc-7.10.2
 
 cache:
   directories:
     - $HOME/.cabal-snapshot
+    - $HOME/.cabal/packages
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+
+matrix:
+  include:
+    - env: CABAL=1.18 GHC=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
+    - env: CABAL=1.22 GHC=7.10.2
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
+    - env: CABAL=head GHC=head
+      compiler: ": #GHC head"
+      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - env: CABAL=head GHC=head
 
 before_install:
-    - unset CC
-    - export PATH=/opt/cabal/${CABAL}/bin:${PATH}       # hvr-installed cabal
-    - export PATH=/opt/ghc/${GHC}/bin:${PATH}           # hvr-installed ghc
+ - unset CC
+ - export PATH=/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH
 
 install:
-    - cabal update
-    - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
+ - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
 
-    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-    - cabal --version
+# check whether current requested install-plan matches cached package-db snapshot
+ - if diff -u installplan.txt $HOME/.cabal-snapshot/installplan.txt;
+   then
+     echo "cabal build-cache HIT";
+     rm -rfv .ghc;
+     cp -a $HOME/.cabal-snapshot/ghc $HOME/.ghc;
+     cp -a $HOME/.cabal-snapshot/lib $HOME/.cabal-snapshot/share $HOME/.cabal-snapshot/bin $HOME/.cabal/;
+   else
+     echo "cabal build-cache MISS";
+     rm -rf $HOME/.cabal-snapshot;
+     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+     cabal install --only-dependencies --enable-tests --enable-benchmarks;
+   fi
 
-    - .travis/install_dependencies.sh
+# snapshot package-db on cache miss
+ - if [ ! -d $HOME/.cabal-snapshot ];
+   then
+      echo "snapshotting package-db to build-cache";
+      mkdir $HOME/.cabal-snapshot;
+      cp -a $HOME/.ghc $HOME/.cabal-snapshot/ghc;
+      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabal-snapshot/;
+   fi
 
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-    # Check the build
-    - cabal configure -v2 -flib-Werror ${MODE}
-    - cabal build
-    - cabal haddock
-#    - cabal test --show-details=always
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
 
-    # Check the source distribution can be generated, built, and installed
-    - cabal sdist
-    - |
-        export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}')
-        cd dist
-        if [ -f "$SRC_TGZ" ]; then
-            cabal install --force-reinstalls ${MODE} ${SRC_TGZ} || exit 1
-        else
-            echo "'$SRC_TGZ': not found"
-            exit 1
-        fi
-
-
-after_failure:
-    - dmesg
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
 
